### PR TITLE
Print "none" instead of "uninitialized value" warnings.

### PR DESCRIPTION
**Pull request by jankratochvil**
Before (parked M3P):
```
My Tesla account has my car registered with the name 'Tesla'.
Use of uninitialized value in printf at vehicle.pl line 14.
Use of uninitialized value in printf at vehicle.pl line 14.
My car is in gear  and is currently going 0 MPH and my odometer is 7589
My latitude is 50.764024, longitide is 15.269074, my heading is 50 degrees and its using 0.00 kWh/mile
My dashcam is Unavailable, sentry mode is disabled and I am not currently near my vehicle
Use of uninitialized value in printf at vehicle.pl line 36.
My battery is at 79%, and is currently charging at 2.00 volts pulling 0.00 Amps
...
```
After:
```
My Tesla account has my car registered with the name 'Tesla'.
My car is in gear none and is currently going none MPH and my odometer is 7589
My latitude is 50.764024, longitide is 15.269074, my heading is 50 degrees and its using 0.00 kWh/mile
My dashcam is Unavailable, sentry mode is disabled and I am not currently near my vehicle
My battery is at 79%, and is currently charging at 2.00 volts pulling none Amps
...
```

### CODE REVIEW

**Comment by stevieb9** [comment]
The problem here is that the gear and speed are sometimes not returned by the Tesla API, but then sometimes are, so I am trying to figure out a better way to sort that issue out (such as a retry).

The Python library I used to use for some of my car projects does the same thing. What I do there is try the call again until those attributes are populated.

Instead of implementing this PR, I'll get on this tomorrow and fix it correctly.

**Comment by jankratochvil** [comment]
FYI I have never seen those defined. But I never tried to use the API while driving, always only when parked && charging cable connected.

**Comment by stevieb9** [comment]
Yeah, gear is populated with one of `P`, `N`, `R` or `D`. I use that in one of my applications for a device in my garage to identify whether the vehicle is parked or not.

Should get this resolved today.

Thanks for your work by the way!

**Comment by stevieb9** [comment]
This is now fixed in the most recent push. I've added a `API_RETRIES` set to 3. If `shift_state` is undefined, it'll retry the call until its populated. If still undefined after the set number of retries, we set the value to `U`, or "unknown".

Also, `speed()` now has a default of `0`. I found that when the car isn't in gear, that value is always `undef`.

**Pull request closed without merging**
